import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import React, { useState, useEffect } from "react";

// Importing hooks from wagmi
import { useAccount, useProvider, useSigner, useContract } from "wagmi";
import { contract_abi, contract_address } from "../constants/constants";

// Connect button component from rainbowkit built on top of wagmi and ethers
import { ConnectButton } from "@rainbow-me/rainbowkit";

export default function Home() {
  // maintaining the current mood and new mood state
  const [currentMood, setCurrentMood] = useState("");
  const [newMood, setNewMood] = useState("");

  // intializaing provider , Signer and the contract
  const { address, isConnected } = useAccount();
  const Provider = useProvider();
  const { data: Signer } = useSigner();
  const Mood_contract = useContract({
    address: contract_address,
    abi: contract_abi,
    signerOrProvider: Signer || Provider,
  });

  // function that fetches the current mood from the contract
  const fetchCurrentMood = async () => {
    try {
      const data = await Mood_contract.getMood();
      console.log(data);
      setCurrentMood(data);
    } catch (err) {
      console.log(err);
    }
  };

  const setMood = async () => {
    try {
      const data = await Mood_contract.setMood(newMood);
      await data.wait();
      console.log(data);
    } catch (err) {
      console.log(err);
    }
  };

  useEffect(() => {
    fetchCurrentMood();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Mood Checker</a>
        </h1>

        <p className={styles.description}>
          The current mood : <a> {currentMood} </a>
        </p>

        <div className={styles.form}>
          <div className={styles.firstrow}>
            <ConnectButton />
          </div>
          <div className={styles.firstrow}>
            <input
              className={styles.input}
              type="text"
              value={newMood}
              placeholder="New Mood to set"
              onChange={(e) => setNewMood(e.target.value)}
            ></input>
          </div>
          <div className={styles.buttonrow}>
            <button onClick={() => setMood()} className={styles.button}>
              Set New Mood 🚀
            </button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/0xdhruva"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built by @0xDhruva
        </a>
        <a href="https://github.com/Dhruv-2003/Web3.StorageDemoApp">Github</a>
      </footer>
    </div>
  );
}
